# Generated by Django 3.2.25 on 2025-07-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Nowy'), ('in_progress', 'W toku'), ('resolved', 'Rozwiązany')], default='new', max_length=12, verbose_name='Status'),
        ),
    ]
