# Generated by Django 3.2.25 on 2025-07-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nowy', 'Nowy'), ('w_toku', 'W toku'), ('rozwiazany', 'Rozwiązany')], default='nowy', max_length=12, verbose_name='Status'),
        ),
    ]
