# Generated by Django 3.2.25 on 2025-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nowy', 'Nowy'), ('w_toku', 'W_toku'), ('rozwiazany', 'Rozwiazany')], default='nowy', max_length=12, verbose_name='Status'),
        ),
    ]
